-- 1. Crear la tabla de normativas por país
create table if not exists normativa_paises (
  id bigint generated by default as identity primary key,
  pais_id text not null unique, -- Ej: 'MX', 'CO'
  pais_nombre text not null,
  marco_curricular text not null,
  terminologia text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Habilitar seguridad
alter table normativa_paises enable row level security;

-- 3. Política de lectura pública
create policy "Permitir lectura publica normativas" on normativa_paises for select using (true);

-- 4. Insertar los datos maestros
insert into normativa_paises (pais_id, pais_nombre, marco_curricular, terminologia) values
('MX', 'México', 'Nueva Escuela Mexicana (NEM)', 'Campos Formativos, Ejes Articuladores, Proyectos Comunitarios, PDA (Procesos de Desarrollo de Aprendizaje)'),
('ES', 'España', 'LOMLOE (Ley Celaá)', 'Situaciones de Aprendizaje, Saberes Básicos, Criterios de Evaluación, Competencias Clave'),
('CO', 'Colombia', 'Lineamientos MEN', 'DBA (Derechos Básicos de Aprendizaje), Estándares de Competencia, Evidencias de Aprendizaje'),
('CL', 'Chile', 'Bases Curriculares Mineduc', 'OA (Objetivos de Aprendizaje), Indicadores de Evaluación, Actitudes, Habilidades'),
('AR', 'Argentina', 'NAP (Consejo Federal)', 'Núcleos de Aprendizaje Prioritarios, Capacidades, Secuencias Didácticas, Propósitos'),
('PE', 'Perú', 'CNEB (Currículo Nacional)', 'Competencias, Capacidades, Desempeños, Enfoques Transversales'),
('US', 'EE. UU. (Español)', 'Common Core State Standards / State Standards', 'Estándares Estatales, WIDA (para ELD), Objetivos de Contenido y Lenguaje'),
('CA', 'Centroamérica', 'Currículos Nacionales Base (CNB)', 'Indicadores de Logro, Competencias Marco, Ejes del Currículo, Áreas Curriculares');

-- Actualizar si ya existen (Upsert)
insert into normativa_paises (pais_id, pais_nombre, marco_curricular, terminologia) values
('MX', 'México', 'Nueva Escuela Mexicana (NEM)', 'Campos Formativos, Ejes Articuladores, Proyectos Comunitarios, PDA (Procesos de Desarrollo de Aprendizaje)'),
('ES', 'España', 'LOMLOE (Ley Celaá)', 'Situaciones de Aprendizaje, Saberes Básicos, Criterios de Evaluación, Competencias Clave'),
('CO', 'Colombia', 'Lineamientos MEN', 'DBA (Derechos Básicos de Aprendizaje), Estándares de Competencia, Evidencias de Aprendizaje'),
('CL', 'Chile', 'Bases Curriculares Mineduc', 'OA (Objetivos de Aprendizaje), Indicadores de Evaluación, Actitudes, Habilidades'),
('AR', 'Argentina', 'NAP (Consejo Federal)', 'Núcleos de Aprendizaje Prioritarios, Capacidades, Secuencias Didácticas, Propósitos'),
('PE', 'Perú', 'CNEB (Currículo Nacional)', 'Competencias, Capacidades, Desempeños, Enfoques Transversales'),
('US', 'EE. UU. (Español)', 'Common Core State Standards / State Standards', 'Estándares Estatales, WIDA (para ELD), Objetivos de Contenido y Lenguaje'),
('CA', 'Centroamérica', 'Currículos Nacionales Base (CNB)', 'Indicadores de Logro, Competencias Marco, Ejes del Currículo, Áreas Curriculares')
on conflict (pais_id) do update set
  marco_curricular = excluded.marco_curricular,
  terminologia = excluded.terminologia;
