-- 1. Crear la tabla de claves API
create table if not exists api_keys (
  id bigint generated by default as identity primary key,
  key_value text not null unique,
  status text default 'active' check (status in ('active', 'exhausted')),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Habilitar seguridad
alter table api_keys enable row level security;

-- 3. Políticas de acceso (Simplificadas para demo)
-- Permitir lectura para obtener claves
create policy "Permitir lectura publica" on api_keys for select using (true);
-- Permitir actualización para marcar como agotadas (en producción esto debería ser más estricto)
create policy "Permitir update publico" on api_keys for update using (true);

-- 4. Función para obtener la siguiente clave disponible (Waterfall)
create or replace function get_valid_api_key()
returns text
language plpgsql
security definer
as $$
declare
  found_key text;
begin
  -- Selecciona la primera clave activa ordenada por ID (la más vieja primero)
  select key_value into found_key
  from api_keys
  where status = 'active'
  order by id asc
  limit 1;
  
  return found_key;
end;
$$;

-- 5. Función para reportar una clave agotada
create or replace function mark_key_exhausted(target_key text)
returns void
language plpgsql
security definer
as $$
begin
  update api_keys
  set status = 'exhausted'
  where key_value = target_key;
end;
$$;

-- 6. (Opcional) Insertar tus claves aquí
-- insert into api_keys (key_value) values 
-- ('TU_CLAVE_1'),
-- ('TU_CLAVE_2'),
-- ('TU_CLAVE_3');
