-- 1. Crear tabla de usuarios autorizados (White List)
create table if not exists usuarios_autorizados (
  id bigint generated by default as identity primary key,
  email text not null unique,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Habilitar seguridad (RLS)
alter table usuarios_autorizados enable row level security;

-- 3. Función segura para verificar si un email está autorizado
-- Esta función permite al frontend consultar si un correo existe sin dar acceso a leer toda la tabla.
create or replace function is_email_authorized(email_check text)
returns boolean
language plpgsql
security definer -- Se ejecuta con permisos de administrador para poder leer la tabla privada
as $$
begin
  return exists (select 1 from usuarios_autorizados where email = email_check);
end;
$$;

-- 4. Insertar usuario administrador (TÚ)
insert into usuarios_autorizados (email) values ('e8727143@gmail.com') on conflict (email) do nothing;
