-- Asegurar que la tabla existe
create table if not exists usuarios_autorizados (
  id bigint generated by default as identity primary key,
  email text not null unique,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Habilitar RLS
alter table usuarios_autorizados enable row level security;

-- Política de lectura pública (para depuración y acceso directo si es necesario)
drop policy if exists "Enable read access for all users" on usuarios_autorizados;
create policy "Enable read access for all users" on usuarios_autorizados for select using (true);

-- Recrear la función de verificación con permisos explícitos
create or replace function is_email_authorized(email_check text)
returns boolean
language plpgsql
security definer
as $$
begin
  return exists (
    select 1 
    from usuarios_autorizados 
    where lower(trim(email)) = lower(trim(email_check))
  );
end;
$$;

-- Otorgar permisos de ejecución a roles anónimos y autenticados
grant execute on function is_email_authorized(text) to anon;
grant execute on function is_email_authorized(text) to authenticated;
grant execute on function is_email_authorized(text) to service_role;

-- Insertar el correo asegurando formato correcto
insert into usuarios_autorizados (email) 
values ('e8727143@gmail.com') 
on conflict (email) do update 
set email = 'e8727143@gmail.com'; -- Asegura que esté en minúsculas y sin espacios
